/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/common/BaseModal.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    ChartCard: typeof import('./src/components/common/ChartCard.vue')['default']
    Checkbox: typeof import('./src/components/ui/Checkbox.vue')['default']
    ConfirmModal: typeof import('./src/components/ConfirmModal.vue')['default']
    CustomDropdown: typeof import('./src/components/CustomDropdown.vue')['default']
    DataTable: typeof import('./src/components/common/DataTable.vue')['default']
    DataTableToolbar: typeof import('./src/components/common/DataTableToolbar.vue')['default']
    FaiFirstPassYieldChart: typeof import('./src/components/common/FaiFirstPassYieldChart.vue')['default']
    ForgotPasswordModal: typeof import('./src/components/ForgotPasswordModal.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    MultiSelectDropdown: typeof import('./src/components/common/MultiSelectDropdown.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PdfViewer: typeof import('./src/components/common/PdfViewer.vue')['default']
    Radio: typeof import('./src/components/ui/Radio.vue')['default']
    RoleBadgeList: typeof import('./src/components/common/RoleBadgeList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/common/SearchInput.vue')['default']
    SingleSelectDropdown: typeof import('./src/components/common/SingleSelectDropdown.vue')['default']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
  }
}
